---

apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: nextcloud
data:
  DB_HOST: postgres-service
  DB_DATABASE: nextcloud
  DB_USERNAME: username

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nextcloud
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=

---
