---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: nextcloud
  labels:
    tier: backend
spec:
  selector:
    app: postgres
    tier: backend
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
#      targetPort:
#      name:

---
