---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: afraid-cron-job
  namespace: 00x56
spec:
  schedule: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: afraid-cron-job
        spec:
          restartPolicy: Never
          containers:
            - name: afraid-cron-job
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              command: [ '/bin/sh', '-c', '/usr/bin/curl -ks https://freedns.afraid.org/dynamic/update.php' ]

---
