---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextcloud
  labels:
    tier: backend
spec:
  selector:
    app: nextcloud
    tier: backend
  type: ClusterIP
  ports:
    - port: 9000
#      targetPort:
#      name:

---
