---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  config : |
    server {
      root /var/www/id-0x56.com/public;
      index index.php index.html;

      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;

        fastcgi_pass php:9000;
        # fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        include fastcgi_params;
      }

      location ~ /\.ht {
        deny all;
      }

      error_log /var/log/nginx/id-0x56.com_error.log;
      access_log /var/log/nginx/id-0x56.com_access.log;
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  DB_DATABASE: database
  DB_USERNAME: username
  DB_PASSWORD: password

---
