---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_URL: https://nextcloud.00x56.com
  NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.00x56.com
  NEXTCLOUD_DATA_DIR: /var/www/html/data
  NEXTCLOUD_UPLOAD_MAX_FILESIZE: 4G
  # postgres
  POSTGRES_HOST: postgres-service.database
  POSTGRES_DB: nextcloud
  POSTGRES_USER: username
  # redis
  REDIS_HOST: redis-service.database

---

apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
data:
  NEXTCLOUD_ADMIN_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=

---
