---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pv-claim
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      type: local
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 350Gi

---
