---

apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: 00x56
  labels:
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  type: ClusterIP
  ports:
    - port: 9000
#      targetPort:
#      name:

---
