---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    tier: backend
spec:
  selector:
    app: mysql
    tier: backend
  type: ClusterIP
  ports:
    - port: 3306
#      targetPort:
#      nodePort:
      protocol: TCP
#      name:

---
