---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: 00x56
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http

---
