---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: 00x56
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
        - name: backend-pv-storage
          persistentVolumeClaim:
            claimName: backend-pv-claim
      containers:
        - name: php
          image: 00x56/php:fpm-alpine
          lifecycle:
            postStart:
              exec:
                command: [ '/bin/sh', '-c', '/var/www/00x56.com/artisan migrate:refresh --seed' ]
          volumeMounts:
            - name: backend-pv-storage
              mountPath: /var/www/00x56.com

---
