---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pv-claim
  namespace: 00x56
spec:
  selector:
    matchLabels:
      tier: backend
      type: local
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---
