---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: database
data:
  DB_HOST: postgres-service
  DB_DATABASE: postgres
  DB_USERNAME: username
  init_db: |
    #!/bin/bash

    set -e
    set -u

    psql -v ON_ERROR_STOP=1 --username 'username' --dbname 'postgres' << EOF
      CREATE DATABASE nextcloud;
      GRANT ALL PRIVILEGES ON DATABASE nextcloud TO username;
    EOF

    psql -v ON_ERROR_STOP=1 --username 'username' --dbname 'postgres' << EOF
      CREATE DATABASE gitlab;
      GRANT ALL PRIVILEGES ON DATABASE gitlab TO username;
    EOF

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=

---
