---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: database
  labels:
    tier: backend
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: backend
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: postgres-config
          configMap:
            name: postgres-config
            items:
              - key: init_db
                path: init_db.sh
      containers:
        - name: postgres
          image: postgres:alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgres-pv-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /docker-entrypoint-initdb.d/init_db.sh
              subPath: init_db.sh
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD

---
