---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv-volume
  namespace: 00x56
  labels:
    app: app
    type: local
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  nfs:
    server: 192.168.88.225
    path: /mnt/nfs_k8s/app

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: 00x56
  labels:
    app: mysql
    type: local
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  nfs:
    server: 192.168.88.225
    path: /mnt/nfs_k8s/mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pv-claim
  namespace: 00x56
spec:
  selector:
    matchLabels:
      app: app
      type: local
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: 00x56
spec:
  selector:
    matchLabels:
      app: mysql
      type: local
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
