---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: 00x56
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: mysql
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
        - name: mysql
          image: mysql:latest
          args: [ "--default_authentication_plugin=mysql_native_password" ]
          volumeMounts:
            - name: mysql-pv-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: 'true'
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD

---
