---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: jenkins
      tier: backend
  template:
    metadata:
      labels:
        app: jenkins
        tier: backend
    spec:
      volumes:
        - name: jenkins-pv-storage
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
        - name: dind-pv-storage
          emptyDir: {}
      containers:
        - name: jenkins
          image: 00x56/jenkins
          volumeMounts:
            - name: jenkins-pv-storage
              mountPath: /var/jenkins_home
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
        - name: dind
          image: docker:20.10-dind
          volumeMounts:
            - name: dind-pv-storage
              mountPath: /var/lib/docker
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ''
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          securityContext:
            privileged: true

---
