---

apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  type: ClusterIP
  ports:
    - port: 9000
#      targetPort:
#      nodePort:
      protocol: TCP
#      name:

---
