---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: database
data:
  DB_HOST: mysql-service
  DB_DATABASE: database
  DB_USERNAME: username
  init_db: |
    CREATE DATABASE IF NOT EXISTS `laravel` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
    GRANT ALL ON `laravel`.* TO 'username'@'%';

    FLUSH PRIVILEGES;

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=

---
