---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    app: mysql
    type: local
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  nfs:
    server: 192.168.88.220
    path: /mnt/nfs_k8s/mysql

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv-volume
  labels:
    app: app
    type: local
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  nfs:
    server: 192.168.88.220
    path: /mnt/nfs_k8s/app

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    app: postgres
    type: local
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  nfs:
    server: 192.168.88.220
    path: /mnt/nfs_k8s/postgres

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv-volume
  labels:
    app: nextcloud
    type: local
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 350Gi
  nfs:
    server: 192.168.88.220
    path: /mnt/nfs_k8s/nextcloud

---
