---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: 00x56
  labels:
    tier: backend
spec:
  selector:
    app: mysql
    tier: backend
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
#      targetPort:
#      name:

---
