---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: 00x56
  labels:
    tier: backend
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-config
          configMap:
            name: mysql-config
            items:
              - key: init_db
                path: init_db.sql
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: 'IfNotPresent'
          args: [ '--default_authentication_plugin=mysql_native_password' ]
          volumeMounts:
            - name: mysql-pv-storage
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /docker-entrypoint-initdb.d/init_db.sql
              subPath: init_db.sql
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: 'true'
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD

---
